management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_local?currentSchema=schema1
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update