apiVersion: v1
kind: Namespace
metadata:
  name: fluentd-java-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-app
  namespace: fluentd-java-ns
  labels:
    app: fluentd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd-app
  template:
    metadata:
      labels:
        app: fluentd-app
    spec:
      containers:
        - name: fluentd-app
          image: fluentd-app:latest
          imagePullPolicy: IfNotPresent